# Spectrum3d 'Makefile' automatically generated by the 'configure' script

VPATH = src:../headers

objects = main.o mainwindow.o onclick.o menu.o display.o events.o geis.o scale.o testrtpool.o

spectrum3d : $(objects)

	gcc  -Wall $(objects) -o spectrum3d `pkg-config jack gstreamer-0.10 gtk+-2.0 --libs --cflags` -lSDL -lSDL_ttf -lGL -lGLU -lutouch-geis

main.o : main.c main.h config.h
	cc -c $< `pkg-config gtk+-2.0 --libs --cflags` 

mainwindow.o : mainwindow.c mainwindow.h config.h
	cc -c $< `pkg-config gstreamer-0.10 gtk+-2.0 --libs --cflags`

onclick.o : onclick.c onclick.h config.h
	cc -c $< `pkg-config gstreamer-0.10 gtk+-2.0 --libs --cflags` 

menu.o : menu.c menu.h config.h
	cc -c $< `pkg-config gtk+-2.0 --libs --cflags`

display.o : display.c display.h config.h
	cc -c $< `pkg-config gstreamer-0.10 --libs --cflags` -lGL -lGLU 

events.o : events.c events.h config.h
	cc -c $< `pkg-config gtk+-2.0 --libs --cflags` -lSDL 

geis.o : geis.c geis.h config.h
	cc -c $< `pkg-config gtk+-2.0 --libs --cflags` -lutouch-geis

scale.o : scale.c scale.h config.h
	cc -c $< -lSDL -lSDL_ttf -lGL -lGLU

testrtpool.o : testrtpool.c testrtpool.h config.h
	cc -c $< `pkg-config gstreamer-0.10 --libs --cflags`

.PHONY : clean
clean :
	-rm spectrum3d $(objects)

prefix=/usr/local
    
install: spectrum3d
	install -m 0755 spectrum3d $(prefix)/bin
	install -m 0777 files/spectrum3d.conf $(prefix)/etc
	-mkdir $(prefix)/share/icons
	install -m 0644 files/spectrum3d.png $(prefix)/share/icons/spectrum3d.png
	install -m 0777 files/spectrum3d.desktop /usr/share/applications
	install -m 0644 files/FreeSans.ttf $(prefix)/share/fonts

.PHONY: install

.PHONY : uninstall
uninstall :
	-rm $(prefix)/bin/spectrum3d $(prefix)/etc/spectrum3d.conf $(prefix)/share/icons/spectrum3d.png /usr/share/applications/spectrum3d.desktop $(prefix)/share/fonts/FreeSans.ttf
